version: '3'
services:
  controller:
    image: ngrinder/controller
    restart: always
    ports:
      - "9000:80"
      - "16001:16001"
      - "12000-12009:12000-12009"
    volumes:
      - ./ngrinder-controller:/opt/ngrinder-controller
  agent:
    image: ngrinder/agent
    restart: always
    links:
      - controller
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - pipeline
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - pipeline

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8989:8080"
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka_test
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - pipeline
  es: # 서비스 이름
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1 # 사용할 도커 이미지
    environment: # 환경 변수 설정
      - node.name=es # 노드의 이름
      - discovery.type=single-node # 단일 노드로 실행
      - discovery.seed_hosts=es # 시드 노드로 현재 노드를 사용
      - ELASTIC_PASSWORD=bkj09270!
      - bootstrap.memory_lock=true # 메모리 잠금 활성화
      - xpack.security.enabled=false # X-Pack 보안 비활성화
      - xpack.security.http.ssl.enabled=false # HTTP SSL 비활성화
      - xpack.security.http.ssl.verification_mode=certificate # HTTP SSL 검증 방법 설정
      - xpack.security.transport.ssl.enabled=false # 전송 SSL 비활성화
      - xpack.security.transport.ssl.verification_mode=certificate # 전송 SSL 검증 방법 설정
      - xpack.license.self_generated.type=basic # 라이선스 유형을 기본으로 설정
    mem_limit: 1073741824 # 최대 메모리 제한 (1GB)
    ulimits: # ulimit 설정
      memlock:
        soft: -1 # 메모리 잠금의 soft 제한 해제
        hard: -1 # 메모리 잠금의 hard 제한 해제
    volumes: # 볼륨 마운트
      - es-data:/usr/share/es/data # 데이터 저장용 볼륨
      - certs:/usr/share/elasticsearch/config/certs # 인증서 저장용 볼륨
    ports: # 포트 바인딩
      - 9200:9200 # 호스트의 9200 포트를 컨테이너의 9200 포트에 연결
  kibana:
    image: kibana:8.7.1
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    ports:
      - 5601:5601
    depends_on:
      - es

volumes:
  certs:
    driver: local
  es-data:
    driver: local


networks:
  pipeline:
    driver: bridge

