version: '3'

services:
  es: # Elasticsearch 서비스 정의
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    restart: always
    environment:
      - node.name=es
      - discovery.type=single-node
      - ELASTIC_PASSWORD=bkj09270!
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.http.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=basic
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/es/data
      - certs:/usr/share/elasticsearch/config/certs
    ports:
      - 9200:9200
    healthcheck: # 컨테이너 건강 상태 확인 설정
      test: # 테스트 명령어
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt http://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s # 테스트 간격
      timeout: 10s # 테스트 시간 초과
      retries: 20 # 재시도 횟수  

volumes: # 볼륨 정의
  es-data: # es-data 볼륨
  certs: # certs 볼륨
