version: '3'

services:
  es: # 서비스 이름
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    restart: always
    environment: # 환경 변수 설정
      - node.name=es # 노드의 이름
      - discovery.type=single-node # 단일 노드로 실행
      - ELASTIC_PASSWORD=bkj09270!
      - bootstrap.memory_lock=true # 메모리 잠금 활성화
      - xpack.security.enabled=false # X-Pack 보안 비활성화
      - xpack.security.http.ssl.enabled=false # HTTP SSL 비활성화
      - xpack.security.http.ssl.verification_mode=certificate # HTTP SSL 검증 방법 설정
      - xpack.security.transport.ssl.enabled=false # 전송 SSL 비활성화
      - xpack.security.transport.ssl.verification_mode=certificate # 전송 SSL 검증 방법 설정
      - xpack.license.self_generated.type=basic # 라이선스 유형을 기본으로 설정
    mem_limit: 1073741824 # 최대 메모리 제한 (1GB)
    ulimits: # ulimit 설정
      memlock:
        soft: -1 # 메모리 잠금의 soft 제한 해제
        hard: -1 # 메모리 잠금의 hard 제한 해제
    volumes: # 볼륨 마운트
      - es-data:/usr/share/es/data # 데이터 저장용 볼륨
      - certs:/usr/share/elasticsearch/config/certs # 인증서 저장용 볼륨
    ports: # 포트 바인딩
      - 9200:9200 # 호스트의 9200 포트를 컨테이너의 9200 포트에 연결

volumes: # 볼륨 정의
  es-data: # es-data 볼륨
  certs: # certs 볼륨
